"""
INJURY IMPACT — real, historical-data-backed PROJ adjustment for a player
currently carrying a real live Questionable/Doubtful designation.
==========================================================================
Loads engine/injury_impact_factors.json (generated by injury_impact_tuner.py
— see that file's own docstring for the full real methodology: median %
change vs. each player's own same-season healthy-week baseline, aggregated
by position + real nflverse injury body part + report status, across 8
real NFL seasons, only kept when at least 30 real observations back it).

Real, disclosed limitation, not a silent gap: this is a position + injury-
type aggregate, not "how THIS specific player has personally played
through THIS injury before" — checked the real numbers in the tuner and
even the best-populated bucket only reaches ~140 real observations across
the WHOLE LEAGUE and 8 seasons combined, meaning any one player's own
career sample for one specific injury is almost always 0-2 real games —
nowhere near enough to trust a personal-specific factor without
fabricating confidence that isn't really there. The league-wide,
position-level real pattern is the honest, defensible version of this
idea; a fake-precise "personal" number would not be.

Degrades to a neutral 1.0 multiplier (no adjustment) whenever: the player
has no live Questionable/Doubtful status, Sleeper hasn't reported a body
part, the body part doesn't normalize to a bucket this table has real
data for, or that bucket exists but never cleared the real sample-size
bar (QB has none at all right now — real finding, not a bug: QBs rarely
draw a Questionable tag for a single, plainly-body-part injury the way
skill-position players do, so 8 real seasons never produced 30+ real
observations for any one QB bucket).
"""
import json
import os

_FACTORS_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "injury_impact_factors.json")

# Sleeper's live `injury_body_part` vocabulary -> the bucket keys used in
# injury_impact_factors.json (nflverse's `report_primary_injury` naming,
# see injury_impact_tuner.py). Must stay in sync with that tuner's own
# INJURY_BUCKET_ALIASES for the reverse (historical-side) normalization.
# Sub-types collapse to their general real bucket (e.g. a torn ACL is
# real, structural knee damage — the "Knee" bucket's real historical
# sample already includes plenty of serious knee injuries alongside
# minor ones, not a mismatch) rather than fragmenting an already-thin
# sample further.
_BODY_PART_ALIASES = {
    "Quadriceps": "Quadriceps",
    "Ribs": "Ribs",
    "Knee - ACL": "Knee", "Knee - ACL + MCL": "Knee", "Knee - MCL": "Knee",
    "Knee - Meniscus": "Knee", "Knee - PCL": "Knee",
    "Shoulder - AC Joint": "Shoulder",
}


def _load_factors():
    if not os.path.exists(_FACTORS_PATH):
        return {}
    try:
        with open(_FACTORS_PATH) as f:
            return json.load(f).get("factors", {})
    except Exception as e:
        print(f"[injury_impact] couldn't read {_FACTORS_PATH} (no live adjustment applied): {e}")
        return {}


_FACTORS = _load_factors()


def normalize_body_part(raw_body_part):
    """Sleeper's raw injury_body_part value -> this table's bucket key,
    or the value unchanged if it's already a real, direct match (the
    common case — most of Sleeper's real values already match nflverse's
    naming exactly)."""
    if not raw_body_part:
        return None
    return _BODY_PART_ALIASES.get(raw_body_part, raw_body_part)


def injury_multiplier(position, injury_status, body_part):
    """1.0 (neutral) unless there's a real, sufficiently-sampled
    historical bucket for this exact (position, body part, status) —
    see this module's docstring for exactly what "sufficiently" means
    and why a per-player-specific number isn't offered instead."""
    if injury_status not in ("Questionable", "Doubtful") or not body_part:
        return 1.0
    key = f"{position}|{normalize_body_part(body_part)}|{injury_status}"
    entry = _FACTORS.get(key)
    if entry is None:
        return 1.0
    return round(1.0 + entry["median_pct_change"], 4)


def injury_adjustment_detail(position, injury_status, body_part):
    """Same lookup as injury_multiplier, but returns the full real record
    (including sample size) for anywhere the app wants to disclose WHY a
    number moved, not just apply it silently — e.g. a player-card
    explanation. None when no real adjustment applies."""
    if injury_status not in ("Questionable", "Doubtful") or not body_part:
        return None
    key = f"{position}|{normalize_body_part(body_part)}|{injury_status}"
    entry = _FACTORS.get(key)
    if entry is None:
        return None
    return {
        "body_part": normalize_body_part(body_part), "status": injury_status,
        "multiplier": round(1.0 + entry["median_pct_change"], 4),
        "median_pct_change": entry["median_pct_change"], "real_sample_size": entry["n"],
    }
